### ISSUE TITLE
Can't change text color of pickerIOSItem

### ISSUE THREAD

**Issue by kostyaVyrodov** [fable-compiler/fable-react-native#15]
I use fable-react-native and I tried to change the color of pickerIOSItem. The current version of PickerIOSItemProperties doesn't allow do it. (We need to extend this type)
This issue has been already fixed in the react-native library. 
[PR here](https://github.com/facebook/react-native/pull/11260)

**Comment by kostyaVyrodov** [comment]
I made a mistake.
I used pickerIOSItem with PickerIOSItemProerties, but I could use pickerItem with PickerItemProperties, which already allow changing color. 
This issue is not actual, so you can close it.
Sorry.
P.S.
I wanted the best, you know the rest :)

**Comment by alfonsogarciacaro** [comment]
Hehe, no worries. Thanks a lot for the info. I'll close the issue then. Please feel free to reopen it if necessary :)
