### ISSUE TITLE
Bad prototype for textInput?

### ISSUE THREAD

**Issue by jacereda** [fable-compiler/fable-react-native#17]
Shouldn't this take `(children: React.ReactElement list)` instead of text?

https://github.com/fable-compiler/fable-react-native/blob/b8585a183ff61bb6bfe288227d15cb100a2ef9e8/src/Fable.Helpers.ReactNative.fs#L1441

**Comment by StachuDotNet** [comment]
Why would it do that?

https://facebook.github.io/react-native/docs/textinput.html for reference.

**Comment by jacereda** [comment]
I'm trying to run the iOS version of https://github.com/SAFE-Stack/SAFE-Nightwatch and I'm getting a `Raw text cannot be used outside of a <Text> tag` error. I think `textInput` isn't terminal and it can contain children.

**Comment by jacereda** [comment]
Maybe not a terminal though... What is the `text` argument supposed to be?

**Comment by alfonsogarciacaro** [comment]
I haven't used RN much myself, @forki have you used this function?

**Comment by ddunlea** [comment]
@jacereda I hit this issue myself some time ago. I implemented a work-around locally. If you use this alternate implementation for `textInput`, it should work
```
let inline textInput (props: ITextInputProperties list) (text:string): React.ReactElement =
    let valueProp = TextInput.TextInputProperties.Value text :> ITextInputProperties
    createElement(RN.TextInput, valueProp :: props, [])
```

I'll submit a PR for https://github.com/ddunlea/fable-react-native/commit/ee7c419eb16b705e317e298e3021a5f935db04b5

**Comment by jacereda** [comment]
Is the `text` argument really necessary? Wouldn't it be better to remove it completely and pass it as part of `props`?

**Comment by ddunlea** [comment]
I wrote it that way so as not to break the signature for existing callers. In my own code where I had no existing code to worry about, I'd been doing exactly what you said.
