### ISSUE TITLE
Add Key property to all elements

### ISSUE THREAD

**Issue by forki** [fable-compiler/fable-react-native#21]
How can we do that?

/cc @vbfox @MangelMaxime @alfonsogarciacaro

**Comment by alfonsogarciacaro** [comment]
Not sure if it's different in RN, in React you use the `Key` attribute for built-in elements and in your custom component you've to define a `key` field (lower case) in your props Pojo record (we currently need to find a solution for the lazy views).

**Comment by forki** [comment]
yesmy question is: how can we add it to this lib?

**Comment by MangelMaxime** [comment]
Sorry, I didn't saw this issue :)

You can add ` | Key of string` to all the DU.

This is what has been done for [ReactLeaflet](https://github.com/fable-compiler/fable-react/blob/master/src/Fable.ReactLeaflet/ReactLeaflet.fs#L26)
