### ISSUE TITLE
Question about Func's

### ISSUE THREAD

**Issue by iyegoroff** [fable-compiler/fable-react-native#24]
Why do you use types like `Func<x, y, z>` instead of `(x -> y -> z)` almost everywhere? It seems that second signature is easier to use:

with Func's
```fsharp
let renderItem (item: FlatListRenderItemInfo<'a>) =
  //...

R.flatList items
  [ RenderItem (Func<_, _>renderItem)
    KeyExtractor (Func<_, _, _>(fun item _ -> itemKey item)) ]
```

with arrows
```fsharp
let renderItem (item: FlatListRenderItemInfo<'a>) =
  //...

R.flatList items
  [ RenderItem renderItem
    KeyExtractor (fun item _ -> itemKey item) ]
```

**Comment by forki** [comment]
/cc @alfonsogcnunez @MangelMaxime

iyegoroff <notifications@github.com> schrieb am Mo., 11. Juni 2018, 04:52:

**Comment by Zaid-Ajaj** [comment]
@iyegoroff if `Func` is being used in the API then it is out-dated. `x -> y -> z` should be used because it compiles down to the uncurried version of the function i.e. `function (x, y) { return z; }` for better inter-operability and it can still be partially applied.

**Comment by alfonsogarciacaro** [comment]
It's as @Zaid-Ajaj says :) Originally Fable compiled curried F# functions as nested JS anonymous functions (`x => y => z`) so we used `Func<int,int,int>` to indicate the function wasn't curried. In most cases the conversion from curried F# function to `Func` (aka delegate in .NET) was done automatically by the F# compiler but in others it was hindering usability, so from Fable 1.x on, we're trying not to compile curried functions as nested lambdas. And in most cases you don't need to use `Func` in signatures any more.

**Comment by iyegoroff** [comment]
@Zaid-Ajaj , @alfonsogarciacaro thanks for the answers!
