### ISSUE TITLE
How to get user's current position?

### ISSUE THREAD

**Issue by thitemple** [fable-compiler/fable-react-native#27]
Hi there,

I'm trying to get the current position of my phone doing this: ```Fable.Import.ReactNative.Globals.Geolocation.getCurrentPosition (fun pos -> Browser.console.log ("currentPosition", pos))```

But this yields the following error:
```undefined is not an object (evaluating _reactNative.Geolocation.getCurrentPosition```

How can I do it?

**Comment by thitemple** [comment]
Nevermind, I realized now i just need to use this:

`Fable.Import.Browser.navigator.geolocation.getCurrentPosition`

**Comment by alfonsogarciacaro** [comment]
Great that you found the solution! I'm closing the issue for now, but please feel free to reopen if you have another question :+1:
