### ISSUE TITLE
Missing currentHeight static property for StatusBar

### ISSUE THREAD

**Issue by thitemple** [fable-compiler/fable-react-native#28]
According to the RN docs the StatusBar api has a static member called `currentHeight` that is available only to Android but its available on the main StatusBar object. 

I thought of adding it here:

https://github.com/fable-compiler/fable-react-native/blob/3966bd126a223d394965897ef988c9fbe9cfdbec/src/Fable.Import.ReactNative.fs#L1900

with something like:
`abstract currentHeight: float with get`

but I'm not sure if it's the right approach, if it is, I'm happy to send a PR or with whatever you think is best

**Comment by alfonsogarciacaro** [comment]
I haven't used much RN but looks like the right place to me :) (if @forki doesn't say anything against) We would happily accept a PR. Please check if the property is also mutable and it'd be nice to also add a doc comment to specify it's only for Android :+1:

**Comment by forki** [comment]
Yes PR please

Alfonso Garcia-Caro <notifications@github.com> schrieb am Mi., 11. Juli
2018, 22:00:
