### ISSUE TITLE
Fable 2.0 support

### ISSUE THREAD

**Issue by klanthier** [fable-compiler/fable-react-native#39]
Hello,

I was wondering if there were plans to get this library up to date with the newest Fable 2.0
Otherwise I will start looking into what is needed to get this working.

Thanks

**Comment by alfonsogarciacaro** [comment]
It shouldn't too difficult to update the library. Probably it only involves updating the Fable.React dependency, removing `Pojo` attributes (if any) and maybe replacing `props: 'P list` with `props: 'P seq` so Fable 2 can try to optimize the lists into arrays.

It'd be great if you could give a shot, [you can use this as reference](https://github.com/fable-compiler/fable-react/commit/4f9d7a1dded3c00e730c5586b24ffc99c17a627f#diff-09d5faf67ab46dc2c5fa0ec4c486c0ce). cc @iyegoroff 

Thanks a lot for your help in advance!
Alfonso

**Comment by iyegoroff** [comment]
>  if there were plans to get this library up to date with the newest Fable 2.0

I don't have such plans.

**Comment by alfonsogarciacaro** [comment]
@icekev Do you want to give a shot at updating the library then? I can try to do it if you don't have time.

**Comment by plentylife** [comment]
Is this why when I add this package to my project, all of a sudden Rider can't find `Fable` package?
