### ISSUE TITLE
Fable.Core 3 support

### ISSUE THREAD

**Issue by mvsmal** [fable-compiler/fable-react-native#48]
Hi, I was wondering if there is a plan to support `Fable.Core 3`?

What is actually the state of this project? I see more and more people prefer Fabulous (Xamarin). So is this project going to be continued? Obviously there is no active development.

**Comment by alfonsogarciacaro** [comment]
Not sure, I don't use RN myself so it's difficult for me to maintain this. I can update things for Fable.Core 3 so the library builds but checking that everything actually works is another thing. @forki and @iyegoroff have been the main contributors so far, but we probably need to look for more volunteers to maintain the library :)

**Comment by forki** [comment]
I'm happy to check it out!

**Comment by forki** [comment]
@alfonsogarciacaro if you find some time to apply the most common fable core 3 issues then I'm happy to test and bring it back to life

**Comment by forki** [comment]
It's almost done. There is a (unlisted) 2.0.0-beta-011 on nuget that has most things converted and only 3 modules left. But the big part is done.

![image](https://user-images.githubusercontent.com/57396/57532928-e5ac0a00-733c-11e9-82fc-e38a03f4fc13.png)

**Comment by forki** [comment]
latest beta is now fully converted

**Comment by forki** [comment]
released as 2.0.0
