### ISSUE TITLE
Please add details about how to use the bindings

### ISSUE THREAD

**Issue by mohan-win** [fable-compiler/fable-react-native#56]
Is it possible for someone to help me to understand how to use this bindings and build a react native app on iOS and on Android ?

**Comment by MangelMaxime** [comment]
Hello, did you try to take a look at https://github.com/SAFE-Stack/SAFE-Nightwatch.

The is a demo project, which is "ready" to use. So in theory you could just clone the repo and clean the unwanted code and start working on your application.

**Comment by mohan-win** [comment]
@MangelMaxime, thanks for the response. SAFE-Nightwatch is failing to build on MAC. Since I'm new to Fable + React native, it would be of great help if we have a more detail about how to use the bindings. I've opened an issue for MAC build failure here,  https://github.com/SAFE-Stack/SAFE-Nightwatch/issues/75

**Comment by forki** [comment]
@tforkmann didn't you get it to compile on Mac? Does it still compile?

mohandev <notifications@github.com> schrieb am Fr., 14. Feb. 2020, 02:47:

**Comment by tforkmann** [comment]
Will try tonight. Don’t have a Mac at work

**Comment by mohan-win** [comment]
@forki, @tforkmann, It was a yarn version issue. Once I switched back to yarn 1.x, it is working nicely.. Thanks for your help...

**Comment by MangelMaxime** [comment]
@mohandev 

I agree having more documentation would be nice. Unfortunately I don't use fable-react-native (only answer people questions ^^) so I can't do it myself.

Please feel free, to send a PR to try filling the gap if you have the time and the desire to help a bit :)

**Comment by mohan-win** [comment]
Sure thing @MangelMaxime, I've just started learning. Once I've experienced with Fable + React Native bit more, I will create this documentation.

**Comment by mohan-win** [comment]
@MangelMaxime, Please take a look at this github project https://github.com/martinmoec/fable-react-native-how-to. This has a simple step by step instructions to set up Fable with React Native. May be we can add a pointer to this github project so that people can easily find it ?

**Comment by forki** [comment]
Sure please link it from the Readme. I'll merge the PR.

mohandev <notifications@github.com> schrieb am Do., 12. März 2020, 07:23:

**Comment by mohan-win** [comment]
Done! https://github.com/fable-compiler/fable-react-native/pull/58

**Comment by forki** [comment]
Thanks
