### ISSUE TITLE
Xcode chokes on .fable directory

### ISSUE THREAD

**Issue by playfulThinking** [fable-compiler/fable-react-native#64]
Sometimes when I have Expo compile a project, and almost always when I do it in Xcode, I get import errors for every Fable library file like this:
```
Unable to resolve module ./.fable/fable-library.3.1.1/Types.js from /Users/michaelfremont/Documents/playthink/code/liarliar-admin/src/App.fs.js
```
The only way I've found to fix this is by renaming the ".fable" directory to "fable" and changing the paths in the generated fs.js files; it then complies, but this is not a workable solution.

Any ideas? Thanks much.

**Comment by alfonsogarciacaro** [comment]
Hmm, so I'm guessing XCode treats directories starting with `.` as really hidden. I guess we can fix this two ways:

1. Enable a CLI option to rename `.fable` folder.
2. Renaming the `.fable` hidden folder to `fable_modules` or similar. It's ignored because it contains a `.gitignore` file not because of the name, and I assume it won't be a breaking change because it's dealt with automatically anyways.

Thoughts? cc @MangelMaxime

**Comment by MangelMaxime** [comment]
I am in favour of "better" defaults so if renaming it to `fable_modules` is transparent we can go this way.

**Comment by playfulThinking** [comment]
That would be awesome!

**Comment by inosik** [comment]
Should we consider moving the directory to `obj/`?

Anyways, Paket needs to be patched then. [It ignores the `.fable/` directory](https://github.com/fsprojects/Paket/blob/e65f8a5760fb9f7014f48d309bf537ff540bf749/src/Paket.Core/PaketConfigFiles/ProjectFile.fs#L1907) when looking for projects. /cc @forki

**Comment by alfonsogarciacaro** [comment]
With Fable 3 when using `--outDir` the .fable hidden folder is located in the outDir and it's normally outside of the .fsproj and `obj` hierarchies.

Ah, true about Paket :/ I think Ionide does something similar. Maybe we could change the .fsproj extension to .fableproj as a trick to avoid this kind of issues...

**Comment by inosik** [comment]
> With Fable 3 when using --outDir the .fable hidden folder is located in the outDir and it's normally outside of the .fsproj and obj hierarchies.

Ah right. `obj/` only makes sense if the output directory is the same as the source directory. I just thought `obj/` would be ignored by most tools in the .NET world and wouldn't show up anywhere.

You're right, Ionide ignores the `.fable/` directory as well: https://github.com/ionide/ionide-vscode-fsharp/blob/652c12430cd759162997ca4a7633da680d200354/release/package.json#L1302

**Comment by alfonsogarciacaro** [comment]
@fremontmj Can you please try with Fable 3.4 and confirm if the issue is solved? Thanks!

**Comment by playfulThinking** [comment]
@alfonsogarciacaro That seems to have done it. So amazed and thankful to the fast reaction to my issue. You guys rock.
