### ISSUE TITLE
Fable 4 incompatibility

### ISSUE THREAD

**Issue by playfulThinking** [fable-compiler/fable-react-native#68]
I updated a very simple project to Fable 4 and got this:
```
./src/fable_modules/Fable.React.Native.3.0.0-alpha001/Fable.ReactNative.Types.fs(1451,76): (1451,78) error FSHARP: The type parameter 'T is not defined. (code 39)
./src/fable_modules/Fable.React.Native.3.0.0-alpha001/Fable.ReactNative.Types.fs(1452,65): (1452,67) error FSHARP: The type parameter 'T is not defined. (code 39)
```

These are the lines that offend:
```
abstract getRowData: (obj -> U2<float, string> -> U2<float, string> -> 'T) option with get, set
abstract getSectionHeaderData: (obj -> U2<float, string> -> 'T) option with get, set
```

This seems to be related to this: https://github.com/fable-compiler/Fable/issues/3248
Apparently this is _not_ a compiler error, but an illegal construction the CLR.

I don't know what these functions do, nor how to fix the declarations. Anybody?

Thanks much!

**Comment by MangelMaxime** [comment]
Hello @fremontmj,

It seemed like the package was already fixed in the Github repository but not published yet.

I just released version 4.0.0, please give it a try.

**Comment by playfulThinking** [comment]
Thank you, I will!

**Comment by MangelMaxime** [comment]
I am closing the issue but feel free to re-open if needed
